name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Config File Write
        run: |
          # main 설정 파일 디렉토리로 이동
          cd ./src/main/resources
          
          # application-mysql.yml
          touch ./application-mysql.yml
          echo "${{secrets.CI_APPLICATION_MYSQL}}" >> ./application-mysql.yml
          
          # application-redis.yml
          touch ./application-redis.yml
          echo "${{ secrets.CI_APPLICATION_REDIS }}" >> ./application-redis.yml
          
          # application-email.yml
          touch ./application-email.yml
          echo "${{ secrets.APPLICATION_EMAIL }}" >> ./application-email.yml
        shell: bash

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build Gradle Wrapper
        run: gradle wrap

      - name: Gradle Build
        run: ./gradlew build
        shell: bash
